image: gradle:6.8.3-jdk11

services:
  - "postgres:latest"

variables:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"
  POSTGRES_DB: test
  POSTGRES_HOST: postgres
  POSTGRES_PORT: 5432
  POSTGRES_USER: postgre
  POSTGRES_PASSWORD: postgresql

before_script:
  - export GRADLE_USER_HOME=`pwd`/.gradle

stages:
  - build
  - test
  - deploy

Build:
  stage: build
  script:
    - gradle build --stacktrace --info


Test:
  stage: test
  script:
    - gradle test
    - gradle jacocoTestReport
    - cat build/reports/jacoco/test/html/index.html
  artifacts:
    when: always
    paths:
      - ./build/reports/*

deployment:
  image: ruby:2.4
  stage: deploy
  before_script:
    - gem install dpl
    - wget -qO- https://cli-assets.heroku.com/install-ubuntu.sh | sh
  script:
    - dpl --provider=heroku --app=$HEROKU_APP_NAME --api-key=$HEROKU_API_KEY
    - export HEROKU_API_KEY=$HEROKU_API_KEY
  environment:
    name: production
    url: https://$HEROKU_APP_NAME.herokuapp.com
  only :
    - master
    - feature/setup-deployment
